# Generated by Django 4.2.24 on 2025-09-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmember",
            name="msg_send_count",
            field=models.IntegerField(default=0),
        ),
    ]
